#!/bin/bash

# find_and_move
# Exercise:
# Find and move files in a directory above a certain size
# Use a nice interface
# Note: for practicing purposes, we're just copying, not moving :)
#
# Improvements: only deals with byte sizes for now
#               could be improved to deal with size suffiyes

# Explain usage
usage()
{
  echo "Usage: $0 -s <size> -src <source_dir> -dest <dest_dir>"
  echo "Usage: $0 --size <size> --source <source_dir> --destination <dest_dir>"
  echo "Usage: $0 <size> <source_dir> <dest_dir>"
  echo "Example: $0 -s 1M -src /home/user/source -dest /home/user/destination"
  echo "Finds files larger than <size> in <source_dir> and moves them to <dest_dir>"
}

# Handle good or bad exits
clean_up()
{
  if [ "$1" = "0" ]; then
    echo "All done!"
  else
    echo "Error occurred... exiting!"
  fi
  exit $1
}

## Constants
SIZE=
SOURCE=
DEST=
TEMP=

while [ "$1" != "" ]; do
  case $1 in
    -h | --help )           usage
                            clean_up 0
                            ;;
    -s | --size )           shift
                            SIZE=$1
                            ;;
    -src | --source )       shift
                            SOURCE=$1
                            ;;
    -dest | --destination ) shift
                            DEST=$1
                            ;;
    * )                     if [ "$SIZE" = "" ]; then
                              SIZE=$1
                            elif [ "$SOURCE" = "" ]; then
                              SOURCE=$1
                            elif [ "$DEST" = "" ]; then
                              DEST=$1
                            #else
                              # nothing, just ignore too many args
                            fi
                            ;;
  esac
  shift
done

echo "Size is $SIZE"
echo "Source is $SOURCE"
echo "Destination is $DEST"

# Create directory if doesn't exit yet
if [ ! -d "$DEST" ]; then
  echo "Creating directory $DEST..."
  mkdir -p "$DEST" # -p adds parents too
  if [ "$?" != "0" ]; then
    echo "Error creating directory $DEST..."
    clean_up 1
  fi
fi

# Now loop through contents of source
for file in $SOURCE/*; do

  # Exclude anything but files
  if [ ! -f "$file" ]; then
    echo "Skipping $file because it is not a file"
    continue
  fi

  # Get the size of the file in bytes
  size_file=$(du "$file" | awk '{print $1}')

  # If bigger specified than we copy
  if [ $size_file -gt $SIZE ]; then
    echo "Copying $file to $DEST"
    cp "$file" "$DEST"
    if [ "$?" != "0" ]; then
      echo "Error copying $file to $DEST"
      clean_up 1
    fi
  else
    echo "Skipping $file, size $size_file is less than $SIZE"
  fi
done

clean_up 0
